version: "3.7"
services:
  grpc:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 9093:9093
    volumes:
      - certsdata:/etc/certs

  rest:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 9091:9091
    command:
      - /bin/restservertls
    volumes:
      - certsdata:/etc/certs

  grpcui:
    image: fguy/grpcui:latest
    restart: always
    environment:
      URL: grpc:9093
    depends_on:
      - grpc
    ports:
      - 8082:8082
    volumes:
      - certsdata:/etc/certs
    command:
      - "grpcui"
      - "-bind"
      - "0.0.0.0"
      - "-port"
      - "8082"
      - "-cert"
      - "/etc/certs/server.crt"
      - "-key"
      - "/etc/certs/server.key"
      - "-insecure"
      - "grpc:9093"

volumes:
  certsdata:
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: ${PWD}/certs
